# Generated by Django 3.1.1 on 2020-09-26 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dependent', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Union',
            new_name='SubDistrict',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='union',
            new_name='subdistrict',
        ),
    ]
