# Generated by Django 3.1.1 on 2020-09-26 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dependent', '0002_auto_20200926_0724'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Division',
            new_name='City',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='division',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='division',
            new_name='city',
        ),
    ]
