# Generated by Django 3.1.1 on 2020-09-26 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dependent', '0003_auto_20200926_1006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Division',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='city',
            new_name='division',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='city',
            new_name='division',
        ),
    ]
