# Generated by Django 3.1.1 on 2020-09-26 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dependent', '0004_auto_20200926_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='father_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='person image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='married_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='mother_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='religion',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
