# Generated by Django 3.1.1 on 2020-09-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependent', '0005_auto_20200926_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, upload_to='person image'),
        ),
    ]
